name: Library

on: [pull_request]

env:
  RUST_LOG: "0"

jobs:
  build:
    name: standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          target: wasm32-unknown-unknown
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all
